services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      # we keep postgres db instead of separate to follow currently used JDBC connection strings
      # POSTGRES_DB:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ${GLOBAL_NETWORK:-kafka}

volumes:
  postgres_data:
    driver: local
